In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr + 2)
print(arr * 3)
print(arr / 2)

[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print(arr[::-1])

[5 4 6 3 2 1]


In [4]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
max_count = counts.max()

print(values[counts == max_count])

for value in values[counts == max_count]:
    print(np.where(x == value)[0])

[1]
[0 5 7 8 9]


In [5]:
import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
max_count = counts.max()

print(values[counts == max_count])

for value in values[counts == max_count]:
    print(np.where(y == value)[0])

[1 3]
[0 1 2]
[4 8 9]


In [6]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print(arr[0, 1])
print(arr[2, 0])

20
70


In [7]:
import numpy as np

manya = np.linspace(10, 100, 25)

print(manya)
print(manya.ndim)
print(manya.shape)
print(manya.size)
print(manya.dtype)
print(manya.nbytes)

transpose = manya.reshape(25, 1)
print(transpose)

print(manya.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [8]:
import numpy as np

ucs420_manya = np.array([[10, 20, 30, 40],
                         [50, 60, 70, 80],
                         [90, 15, 20, 35]])

print("Mean:", np.mean(ucs420_manya))
print("Median:", np.median(ucs420_manya))
print("Max:", np.max(ucs420_manya))
print("Min:", np.min(ucs420_manya))
print("Unique:", np.unique(ucs420_manya))

reshaped_ucs420_manya = ucs420_manya.reshape(4, 3)
print(reshaped_ucs420_manya)

resized_ucs420_manya = np.resize(ucs420_manya, (2, 3))
print(resized_ucs420_manya)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique: [10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
