In [2]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

temperature = temperature + 2
print(temperature)

fahrenheit = (9/5) * temperature + 32
print(fahrenheit)

result = temperature[temperature > 32]
print(result)

print(np.sum(temperature > 32))

[27 30 33 37 40 29 35 42]
[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
[33 37 40 35 42]
5


In [3]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print(np.sum(steps))
print(np.mean(steps))
print(np.max(steps))
print(np.min(steps))

print(np.sum(steps, axis=0))
print(np.sum(steps, axis=1))

print(np.argmax(steps))
print(np.unravel_index(np.argmax(steps), steps.shape))

84200
7016.666666666667
9500
4500
[26500 27300 30400]
[18300 24500 14400 27000]
11
(np.int64(3), np.int64(2))


In [4]:
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])

subset = original[1:5]
subset[0] = 999

print(original)
print(subset)

copied = original[1:5].copy()
copied[0] = 500

print(original)
print(copied)

[  1 999   3   4   5   6]
[999   3   4   5]
[  1 999   3   4   5   6]
[500   3   4   5]


In [5]:
arr = np.arange(1, 13).reshape(3, 4)

print(arr)

print(arr[0])
print(arr[-1])
print(arr[:, 1])
print(arr[1:3, 2:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[ 9 10 11 12]
[ 2  6 10]
[[ 7  8]
 [11 12]]


In [6]:
flat = arr.flatten()
ravel = arr.ravel()

print(flat)
print(ravel)

ravel[0] = 100
print(arr)

flat[1] = 200
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [7]:
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(3, 4)
2
12
int64


In [8]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print(X.shape)
print(X.ndim)

print(X.T)

print(X.T @ X)

(4, 3)
2
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


In [9]:
inverse = np.linalg.inv(X.T @ X)
print(inverse)

beta = inverse @ X.T @ y
print(beta)

[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
[-0.15921454  0.14083853 10.06302242]


In [10]:
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])

new_user = np.array([5, 40, 7])

prediction = new_user @ beta

print(prediction)

Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587
75.27862544779117
